### ISSUE TITLE
Breaking changes in `v2.0.0`

### ISSUE THREAD

**Issue by smridge** [coverallsapp/orb#27]
I'm not entirely sure how the copies are managed for https://github.com/coverallsapp/orb/releases. However, it would be good to specify https://github.com/coverallsapp/orb/pull/22 was a `BREAKING CHANGE` by removing the `path_to_lcov` key.

**Comment by mrexox** [comment]
Thank you. I've added a note in [v2.0.0][https://github.com/coverallsapp/orb/releases/tag/v2.0.0] release description
