### ISSUE TITLE
Orb exits 1 without any debugging information

### ISSUE THREAD

**Issue by josegonzalez** [coverallsapp/orb#36]
Can we have a debug variable that sets `set -x` if it's available? It isn't super clear what the error is based on the output here...

<img width="654" alt="Screenshot 2023-06-21 at 5 49 52 PM" src="https://github.com/coverallsapp/orb/assets/65675/aada059a-42d7-4bea-b057-1b50b2645cad">

My config:

```
- coveralls/upload:
          coverage_file: << parameters.working_directory >>/lcov.info
          coverage_format: lcov
```

**Comment by afinetooth** [comment]
@josegonzalez in #48 we have added a `debug` parameter to the `coveralls/upload` command that replaces `verbose` (deprecated) and does two (2) things:

1. Enables `set -x` debugging throughout entire script including setup steps like downloading, verifying and calling the binary; and
2. Adds the `--debug` flag to all `coveralls` commands to enable verbose output from the Coveralls API.

**Comment by josegonzalez** [comment]
Thanks!
