### ISSUE TITLE
Does this actually work in parallel?

### ISSUE THREAD

**Issue by paulfalgout** [coverallsapp/orb#4]
I can't get this orb to work because of https://github.com/coverallsapp/orb/pull/3

But digging in, and trying to manually run what this orb is doing I don't see how this will ever work.

On circleci the jobs in parallel have the same build number, but once the parallel jobs are completed and the job calling the webhook with `payload[build_num]=$CIRCLE_BUILD_NUM` that job is a new build number.  So the result is `"{"error":"No build matching CI build number 2757 found"}"`  And I don't see how the webhook could be called on the parallel job as which parallel job would we do it on?  How do we know when all the jobs are completed other than running a new job that depends on the parallel run.

You can see the behavior here: https://circleci.com/workflow-run/6f4fb4ef-59ef-4311-a1dc-1462b7750687

I don't think it's possible for the orb to support parallel builds on circle ci until the build number can support the workspace id which is part of this PR: https://github.com/nickmerwin/node-coveralls/pull/205

Ideally the webhook could use something other than the build number such as the service job id.. that'd make this task at least _possible_  But I don't think this orb is going to work for parallel until fixes are made elsewhere in the ecosystem.

**Comment by kelvintyb** [comment]
+1 to this, facing this exact same issue. 

The workaround I'm probably going to go with in the interim is using the orb for the parallel tests, then pass the $CIRCLE_BUILD_NUM env variable into the workspace (see [this](https://discuss.circleci.com/t/pass-initial-circle-build-num-to-all-jobs-of-the-workflow/17080)), and reference that value in the curl call to the Coveralls webhook to indicate that the parallel build is done.

**Comment by nickmerwin** [comment]
Hi @paulfalgout and @kelvintyb, we've released a [new version](https://circleci.com/orbs/registry/orb/coveralls/coveralls) that should fix the issues you described.

Closing this issue for now, but please let me know if you still see a problem.

Thank you!
