### ISSUE TITLE
Broken w/ coveralls reporter v0.6.14

### ISSUE THREAD

**Issue by JustinAiken** [coverallsapp/orb#43]
In [v0.6.14](https://github.com/coverallsapp/coverage-reporter/releases/tag/v0.6.14), the binary changes from `coveralls` to `coveralls-linux` -> https://github.com/coverallsapp/coverage-reporter/compare/v0.6.13...v0.6.14#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L84

As a result on CI using this orb:

```
coveralls-linux.tar.gz: OK
Parsing args
Dry run - 0
Reporting coverage
+ ./coveralls report --no-fail
/bin/bash: line 74: ./coveralls: No such file or directory

Exited with code exit status 127
```

**Comment by JustinAiken** [comment]
```bash

> curl -sLO https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz
> tar -xzf coveralls-linux.tar.gz
> tree
.
├── coveralls-checksums.txt
├── coveralls-linux
└── coveralls-linux.tar.gz
```

**Comment by afinetooth** [comment]
Thank you, @JustinAiken.

We're going to remove that release for now. Please give us 10-15.

**Comment by afinetooth** [comment]
@JustinAiken we have pulled that release (`0.6.14`). Please let me know if you next run doesn't work (with `0.6.13` of coverage-reporter).

**Comment by afinetooth** [comment]
For any new visitors, this issue is **resolved**, but I will leave it open for a while longer for anyone just discovering the error in their build logs today.

**Fix**:
The fix is to simply re-run your CI build. The next run should succeed and the version of coverage reporter shown in the output should be `v0.6.13`

**Comment by JustinAiken** [comment]
> Please let me know if you next run doesn't work

One long CI run later, confirm fixed! ✅ 
Thanks for the quick resolution!
