### ISSUE TITLE
Broken w/ reporter v0.6.14

### ISSUE THREAD

**Issue by amc6** [coverallsapp/orb#44]
This seems very similar to this issue https://github.com/coverallsapp/orb/issues/43 but the error is slightly different. The timing lines up with the release of [v0.6.14](https://github.com/coverallsapp/coverage-reporter/releases/tag/v0.6.14)

The docker image I am using is based off of cimg/openjdk:15.0.2 if that's helpful.

```
coveralls-linux.tar.gz: OK
Parsing args
Dry run - 0
Reporting coverage
+ ./coveralls report --no-fail
./coveralls: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

Exited with code exit status 127
CircleCI received exit code 127
```

**Comment by JustinAiken** [comment]
👍, just started seeing the same thing on our pipeline

**Comment by afinetooth** [comment]
@amc6 @JustinAiken we just pulled that release. Please try again to grab the latest, or just, on the orb, re-run. It should grab `v0.6.13`. Let me know if not.

**Comment by amc6** [comment]
That fixed it. Thanks!

**Comment by JustinAiken** [comment]
Yep, all fixed here too!  💚
