### ISSUE TITLE
Search for all lcov.info in given folder

### ISSUE THREAD

**Issue by blacelle** [coverallsapp/orb#9]
It seems the orb takes as `path_to_lcov` parameter a single file path. Would it be relevant/possible to search for any lcov.info files in given folder, if `path_to_lcov` is a folder?

**Comment by mrexox** [comment]
Hey! With `coveralls/coveralls@2.0.0` version it will look for all files that can be reported (not even LCOV files but many more, see: https://github.com/coverallsapp/coverage-reporter#supported-coverage-file-types).
